# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    working_directory: /
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: pwd & yarn build  & ls
      - run: mkdir -p workspace
      - run: cp -r ./ workspace/
      - persist_to_workspace:
          root: workspace
          paths: .
  deploy: # this can be any name you choose
    executor: node/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /workspace
      - run:
          name: Install firebase
          command: npm install --save-dev firebase-tools & ls
      - run:
          name: Deploy app to Firebase Hosting
          command: pwd & ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          # filters:
          #   branches:
          #     only: main # only deploy when on main
