# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install node:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          node-version: '14' 
      - run:
          name: node version
          command: node -v
  test:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          node-version: '14' 
      - run:
          name: yarn test
          command: yarn test

workflows:
  test-workflow:
    jobs:
      - install node
      - test
