# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_test: # this can be any name you choose
    working_directory: ~/mern-starter
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/mern-starter
          cache-path: node_modules
          override-ci-command: npm i --legacy-peer-dep
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - run:
          name: Check
          command: pwd & ls
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy: # this can be any name you choose
    docker:
      # The primary container is an instance of the first image listed. The job's commands run in this container.
      - image: cimg/node:current
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Check
          command: pwd & ls
      - run:
          name: Deploy app to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
  build:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  release:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn
      - attach_workspace:
          at: ~/project
      - run:
          command: node tag-release.js
  notify:
    parameters:
      pull_request:
        type: env_var_name
        default: CIRCLE_PULL_REQUEST
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14'
      - node/install-packages:
          pkg-manager: yarn
      - attach_workspace:
          at: ~/project
      - run:
          command: node slack-notify.js

workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
  tag-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
  slack-notify:
    when:
      condition:
        - not: <<parameters.pull_request>>
    jobs:
      - notify
